#!/usr/bin/env Rscript
# =============================================================================
# FIND AND CROSS-CHECK ABCD TWINS ACROSS MULTIPLE DATA SOURCES
# =============================================================================
# Author: Ada Kepinska
# Date: 2025-02-19
#
# Purpose: Identify twin pairs in ABCD using multiple independent sources
#          and cross-reference them for validation.
#
# Sources:
#   1. PCRelate kinship (from GENESIS, run on smokescreen genotype data)
#   2. ABCD-provided gen_y_pihat.csv (official pihat + zygosity from release 5.1)
#   3. Demographic/family structure (rel_family_id + rel_birth_id from abcd_y_lt)
#
# Key insight: MZ twins can be identified genetically (kinship ~ 0.5, k0 ~ 0),
#   but DZ twins are genetically indistinguishable from full siblings (kinship ~ 0.25).
#   We need the birth ID (same birthdate within family) to separate DZ twins from sibs.
#
# Outputs:
#   - all_twin_pairs_crosschecked.csv  (master file with all sources)
#   - mz_twins_final.csv
#   - dz_twins_final.csv
#   - non_twin_siblings.csv
#   - twin_individuals.csv             (one row per person)
#   - twin_crosscheck_summary.txt
#
# ABCD Data requirements:
#   - ABCD Study release 5.1 (or similar)
#   - Genotype data: smokescreen array, processed through GENESIS/PCRelate pipeline
#   - Files: gen_y_pihat.csv, abcd_y_lt (longitudinal tracking / demographics)
#   - Data access via: https://nda.nih.gov/abcd/
# =============================================================================

suppressPackageStartupMessages({
  library(data.table)
  library(dplyr)
  library(tidyr)
})

cat("=============================================================\n")
cat("  ABCD TWIN IDENTIFICATION & CROSS-CHECK\n")
cat("=============================================================\n\n")

# =============================================================================
# USER CONFIGURATION — update all paths before running
# =============================================================================

PROJECT_DIR  <- "~/your_project_directory"                   # Root of your project

# Source 1: PCRelate results (RDS output from your GENESIS pipeline)
# Generated by running PCRelate on smokescreen genotype data
PCRELATE_FILE <- file.path(PROJECT_DIR, "data/genomics/PCRelate_results.rds")

# Source 2: ABCD official gen_y_pihat.csv
# Downloaded from NDA, ABCD release 5.1 (or your release)
# Contains: src_subject_id, genetic_paired_subjectid_1..4, genetic_pi_hat_1..4,
#           genetic_zygosity_status_1..4, rel_family_id, rel_birth_id
PIHAT_FILE <- file.path(PROJECT_DIR, "data/abcd/gen_y_pihat.csv")

# Source 3: Cleaned demographics / family structure file (baseline timepoint)
# Derived from abcd_y_lt (ABCD longitudinal tracking instrument)
# Must contain: src_subject_id, rel_family_id, rel_birth_id
DEMO_FILE <- file.path(PROJECT_DIR, "data/abcd/abcd_y_lt_baseline_cleaned.csv")

# Output directory
OUTPUT_DIR <- file.path(PROJECT_DIR, "outputs/twin_identification")
dir.create(OUTPUT_DIR, recursive = TRUE, showWarnings = FALSE)

# =============================================================================
# THRESHOLDS (validated against ABCD genotype data)
# =============================================================================

# MZ twins: kinship ~ 0.5, k0 ~ 0, k2 ~ 1
MZ_KIN_MIN  <- 0.45
MZ_K0_MAX   <- 0.02

# DZ twins / full siblings: kinship ~ 0.25
DZ_KIN_MIN  <- 0.20
DZ_KIN_MAX  <- 0.35

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

# Create canonical pair key (alphabetically ordered) for deduplication
make_pair_key <- function(id1, id2) {
  id1 <- as.character(id1)
  id2 <- as.character(id2)
  ifelse(id1 < id2,
         paste(id1, id2, sep = "::"),
         paste(id2, id1, sep = "::"))
}

# Split pair key back into IDs
split_pair_key <- function(pair_key) {
  parts <- strsplit(pair_key, "::", fixed = TRUE)
  data.table(
    id1 = sapply(parts, `[`, 1),
    id2 = sapply(parts, `[`, 2)
  )
}

# =============================================================================
# SOURCE 1: PCRelate KINSHIP (GENESIS)
# =============================================================================

cat("-------------------------------------------------------------\n")
cat("SOURCE 1: PCRelate Kinship (GENESIS)\n")
cat("-------------------------------------------------------------\n\n")

if (file.exists(PCRELATE_FILE)) {
  pcrelate <- readRDS(PCRELATE_FILE)
  kinship_pairs <- as.data.table(pcrelate$kinBtwn)
  
  # Calculate k1 and PI_HAT if not already present
  if (!"k1" %in% names(kinship_pairs)) {
    kinship_pairs[, k1 := 1 - k2 - k0]
  }
  if (!"PI_HAT" %in% names(kinship_pairs)) {
    kinship_pairs[, PI_HAT := k2 + 0.5 * k1]
    kinship_pairs[, PI_HAT := pmin(pmax(PI_HAT, 0), 1)]
  }
  
  cat("  Total pairwise comparisons:", nrow(kinship_pairs), "\n\n")
  
  # --- MZ twins ---
  mz_pcrelate <- kinship_pairs[kin > MZ_KIN_MIN & k0 < MZ_K0_MAX]
  mz_pcrelate[, pair_key := make_pair_key(ID1, ID2)]
  mz_pcrelate[, zygosity_pcrelate := "MZ"]
  
  mz_individuals_pcrelate <- unique(c(mz_pcrelate$ID1, mz_pcrelate$ID2))
  
  cat("  MZ candidates (kin >", MZ_KIN_MIN, ", k0 <", MZ_K0_MAX, "):\n")
  cat("    Pairs:", nrow(mz_pcrelate), "\n")
  cat("    Individuals:", length(mz_individuals_pcrelate), "\n")
  cat("    Kinship summary:\n")
  print(summary(mz_pcrelate$kin))
  cat("    k0 summary:\n")
  print(summary(mz_pcrelate$k0))
  cat("    k2 summary:\n")
  print(summary(mz_pcrelate$k2))
  
  # --- DZ / sibling candidates ---
  dz_sib_pcrelate <- kinship_pairs[kin > DZ_KIN_MIN & kin < DZ_KIN_MAX]
  dz_sib_pcrelate[, pair_key := make_pair_key(ID1, ID2)]
  dz_sib_pcrelate[, zygosity_pcrelate := "DZ_or_sib"]
  
  dz_sib_individuals <- unique(c(dz_sib_pcrelate$ID1, dz_sib_pcrelate$ID2))
  
  cat("\n  DZ/Sibling candidates (kin", DZ_KIN_MIN, "-", DZ_KIN_MAX, "):\n")
  cat("    Pairs:", nrow(dz_sib_pcrelate), "\n")
  cat("    Individuals:", length(dz_sib_individuals), "\n")
  
  # Combine for Source 1
  src1_pairs <- rbind(
    mz_pcrelate[, .(pair_key, ID1, ID2, kin, k0, k1, k2, PI_HAT, zygosity_pcrelate)],
    dz_sib_pcrelate[, .(pair_key, ID1, ID2, kin, k0, k1, k2, PI_HAT, zygosity_pcrelate)]
  )
  src1_pairs[, source1_pcrelate := TRUE]
  
  cat("\n  Total Source 1 twin/sib candidate pairs:", nrow(src1_pairs), "\n\n")
  
} else {
  cat("  WARNING: PCRelate file not found at:", PCRELATE_FILE, "\n")
  cat("  Skipping Source 1.\n\n")
  src1_pairs <- data.table(
    pair_key = character(), ID1 = character(), ID2 = character(),
    kin = numeric(), k0 = numeric(), k1 = numeric(), k2 = numeric(),
    PI_HAT = numeric(), zygosity_pcrelate = character(),
    source1_pcrelate = logical()
  )
}

# =============================================================================
# SOURCE 2: ABCD OFFICIAL gen_y_pihat.csv (genetic pihat + zygosity)
# =============================================================================
# Wide-format columns:
#   genetic_paired_subjectid_1..4  — co-twin/relative subject IDs
#   genetic_pi_hat_1..4            — pihat for each pairing
#   genetic_zygosity_status_1..4   — zygosity code for each pairing
#
# Zygosity codes (from ABCD data dictionary):
#   1 = MZ (monozygotic)
#   2 = DZ (dizygotic)
#   3 = sibling (not twin)
#   NA = no genetic pairing data
# =============================================================================

cat("-------------------------------------------------------------\n")
cat("SOURCE 2: ABCD gen_y_pihat.csv (genetic pihat + zygosity)\n")
cat("-------------------------------------------------------------\n\n")

if (file.exists(PIHAT_FILE)) {
  pihat_raw <- fread(PIHAT_FILE, na.strings = c("", "NA"))
  cat("  Loaded:", nrow(pihat_raw), "rows,", ncol(pihat_raw), "columns\n\n")
  
  # Extract pairs from the wide-format genetic columns
  src2_list <- list()
  
  for (i in 1:4) {
    paired_col <- paste0("genetic_paired_subjectid_", i)
    pihat_col  <- paste0("genetic_pi_hat_", i)
    zyg_col    <- paste0("genetic_zygosity_status_", i)
    
    if (!paired_col %in% names(pihat_raw)) next
    
    tmp <- pihat_raw[!is.na(get(paired_col)) & get(paired_col) != "",
                     .(src_subject_id, paired_id = get(paired_col))]
    
    if (pihat_col %in% names(pihat_raw)) {
      tmp$pihat_abcd <- pihat_raw[!is.na(get(paired_col)) & get(paired_col) != "",
                                  get(pihat_col)]
    }
    if (zyg_col %in% names(pihat_raw)) {
      tmp$zygosity_abcd_code <- pihat_raw[!is.na(get(paired_col)) & get(paired_col) != "",
                                          get(zyg_col)]
    }
    
    tmp$pair_slot <- i
    
    if (nrow(tmp) > 0) {
      src2_list[[i]] <- tmp
      cat("  Slot", i, ":", nrow(tmp), "pairings found\n")
    }
  }
  
  # Also extract rel_birth_id from pihat file for later comparison
  if ("rel_birth_id" %in% names(pihat_raw)) {
    pihat_birth_ids <- pihat_raw[, .(src_subject_id = as.character(src_subject_id),
                                     rel_birth_id_pihat = rel_birth_id,
                                     rel_family_id_pihat = rel_family_id)]
  } else {
    pihat_birth_ids <- NULL
  }
  
  if (length(src2_list) > 0) {
    src2_raw <- rbindlist(src2_list, fill = TRUE)
    
    src2_pairs <- src2_raw[, .(
      id1 = as.character(src_subject_id),
      id2 = as.character(paired_id),
      pihat_abcd = pihat_abcd,
      zygosity_abcd_code = zygosity_abcd_code
    )]
    
    src2_pairs[, pair_key := make_pair_key(id1, id2)]
    src2_pairs <- src2_pairs[!duplicated(pair_key)]
    
    # Standardize zygosity codes: 1 = MZ, 2 = DZ, 3 = sibling
    src2_pairs[, zygosity_abcd := fcase(
      zygosity_abcd_code == 1, "MZ",
      zygosity_abcd_code == 2, "DZ",
      zygosity_abcd_code == 3, "sibling",
      default = "Unknown"
    )]
    
    src2_pairs[, source2_abcd_pihat := TRUE]
    
    cat("\n  Total unique Source 2 pairs:", nrow(src2_pairs), "\n")
    cat("\n  ABCD zygosity distribution:\n")
    print(table(src2_pairs$zygosity_abcd, useNA = "ifany"))
    
    cat("\n  ABCD pihat summary (all pairs):\n")
    print(summary(src2_pairs$pihat_abcd))
    
    cat("\n  Pihat by ABCD zygosity code:\n")
    src2_pairs[, .(mean_pihat = mean(pihat_abcd, na.rm = TRUE),
                   median_pihat = median(pihat_abcd, na.rm = TRUE),
                   min_pihat = min(pihat_abcd, na.rm = TRUE),
                   max_pihat = max(pihat_abcd, na.rm = TRUE),
                   n = .N), by = zygosity_abcd] %>% print()
    cat("\n")
    
  } else {
    cat("  No genetic pairing data found.\n\n")
    src2_pairs <- data.table(
      pair_key = character(), id1 = character(), id2 = character(),
      pihat_abcd = numeric(), zygosity_abcd = character(),
      zygosity_abcd_code = integer(), source2_abcd_pihat = logical()
    )
  }
  
} else {
  cat("  WARNING: gen_y_pihat.csv not found at:", PIHAT_FILE, "\n\n")
  src2_pairs <- data.table(
    pair_key = character(), id1 = character(), id2 = character(),
    pihat_abcd = numeric(), zygosity_abcd = character(),
    zygosity_abcd_code = integer(), source2_abcd_pihat = logical()
  )
  pihat_birth_ids <- NULL
}

# =============================================================================
# SOURCE 3: CLEANED DEMOGRAPHICS (rel_family_id + rel_birth_id)
# Loaded from cleaned abcd_y_lt (may have fewer subjects than gen_y_pihat)
# =============================================================================

cat("-------------------------------------------------------------\n")
cat("SOURCE 3: Cleaned Demographics (rel_family_id + rel_birth_id)\n")
cat("-------------------------------------------------------------\n\n")

if (file.exists(DEMO_FILE)) {
  demo_raw <- fread(DEMO_FILE, na.strings = c("", "NA"))
  cat("  Loaded:", nrow(demo_raw), "rows\n")
  
  has_family <- "rel_family_id" %in% names(demo_raw)
  has_birth  <- "rel_birth_id"  %in% names(demo_raw)
  
  cat("  rel_family_id present:", has_family, "\n")
  cat("  rel_birth_id present:", has_birth, "\n")
  
  # --- Compare subject overlap between gen_y_pihat and cleaned abcd_y_lt ---
  if (exists("pihat_raw") && nrow(pihat_raw) > 0) {
    pihat_ids <- as.character(pihat_raw$src_subject_id)
    demo_ids  <- as.character(demo_raw$src_subject_id)
    
    cat("\n  --- FILE COMPARISON: gen_y_pihat vs cleaned abcd_y_lt ---\n")
    cat("  gen_y_pihat subjects:", length(pihat_ids), "\n")
    cat("  cleaned abcd_y_lt subjects:", length(demo_ids), "\n")
    cat("  In both:", length(intersect(pihat_ids, demo_ids)), "\n")
    cat("  In gen_y_pihat only:", length(setdiff(pihat_ids, demo_ids)), "\n")
    cat("  In cleaned abcd_y_lt only:", length(setdiff(demo_ids, pihat_ids)), "\n")
    
    # Compare birth IDs
    if (has_birth && !is.null(pihat_birth_ids)) {
      demo_births <- demo_raw[, .(src_subject_id = as.character(src_subject_id),
                                  rel_birth_id_demo = rel_birth_id)]
      birth_compare <- merge(pihat_birth_ids, demo_births,
                             by = "src_subject_id", all = TRUE)
      n_both <- sum(!is.na(birth_compare$rel_birth_id_pihat) & 
                      !is.na(birth_compare$rel_birth_id_demo))
      n_agree <- sum(birth_compare$rel_birth_id_pihat == birth_compare$rel_birth_id_demo,
                     na.rm = TRUE)
      cat("  Birth IDs in common:", n_both, "\n")
      cat("  Birth IDs agree:", n_agree, "\n")
      if (n_both > n_agree) {
        cat("  !! Birth IDs DISAGREE:", n_both - n_agree, "subjects\n")
      }
    }
    cat("\n")
  }
  
  if (has_family & has_birth) {
    birth_ids <- demo_raw[, .(src_subject_id = as.character(src_subject_id),
                              rel_family_id, rel_birth_id)]
    
    # Twins/triplets = people sharing the same rel_birth_id
    birth_counts <- birth_ids[, .N, by = rel_birth_id]
    
    cat("\n  Birth ID group sizes (1 = singleton, 2 = twin, 3 = triplet):\n")
    print(table(birth_counts$N))
    
    twin_birth_ids <- birth_counts[N >= 2, rel_birth_id]
    twins_demo <- birth_ids[rel_birth_id %in% twin_birth_ids]
    
    cat("\n  Individuals sharing a birth ID (twins/triplets):", nrow(twins_demo), "\n")
    
    # Create all pairwise combinations within each birth ID group
    src3_list <- list()
    for (bid in twin_birth_ids) {
      ids_in_group <- twins_demo[rel_birth_id == bid, src_subject_id]
      if (length(ids_in_group) >= 2) {
        pair_combos <- combn(sort(ids_in_group), 2)
        src3_list[[as.character(bid)]] <- data.table(
          id1 = pair_combos[1, ],
          id2 = pair_combos[2, ],
          rel_birth_id = bid,
          rel_family_id = twins_demo[rel_birth_id == bid, rel_family_id[1]],
          group_size = length(ids_in_group)
        )
      }
    }
    
    src3_pairs <- rbindlist(src3_list)
    src3_pairs[, pair_key := make_pair_key(id1, id2)]
    src3_pairs[, source3_demo := TRUE]
    src3_pairs[, birth_group_type := fcase(
      group_size == 2, "twin_pair",
      group_size == 3, "triplet",
      group_size > 3,  "multiplet",
      default = "unknown"
    )]
    
    cat("  Twin/triplet pairs from demographics:", nrow(src3_pairs), "\n")
    cat("  Breakdown:\n")
    print(table(src3_pairs$birth_group_type))
    
    src3_individuals <- unique(c(src3_pairs$id1, src3_pairs$id2))
    cat("  Unique individuals:", length(src3_individuals), "\n\n")
    
  } else {
    cat("  WARNING: Missing rel_family_id or rel_birth_id.\n")
    src3_pairs <- data.table(
      pair_key = character(), id1 = character(), id2 = character(),
      rel_birth_id = character(), source3_demo = logical()
    )
  }
  
} else {
  cat("  WARNING: Demographics file not found at:", DEMO_FILE, "\n")
  src3_pairs <- data.table(
    pair_key = character(), id1 = character(), id2 = character(),
    rel_birth_id = character(), source3_demo = logical()
  )
}

# =============================================================================
# CROSS-CHECK: MERGE ALL SOURCES
# =============================================================================

cat("=============================================================\n")
cat("CROSS-CHECKING ALL SOURCES\n")
cat("=============================================================\n\n")

# Collect all unique pair keys
all_pair_keys <- unique(c(
  if (nrow(src1_pairs) > 0) src1_pairs$pair_key else character(),
  if (nrow(src2_pairs) > 0) src2_pairs$pair_key else character(),
  if (nrow(src3_pairs) > 0) src3_pairs$pair_key else character()
))

cat("Total unique pair keys across all sources:", length(all_pair_keys), "\n\n")

# Build master table
master <- data.table(pair_key = all_pair_keys)
master <- cbind(master, split_pair_key(master$pair_key))

# --- Merge Source 1: PCRelate ---
if (nrow(src1_pairs) > 0) {
  src1_merge <- src1_pairs[, .(pair_key, source1_pcrelate,
                               kin_pcrelate = kin,
                               k0_pcrelate = k0, k1_pcrelate = k1, k2_pcrelate = k2,
                               pihat_pcrelate = PI_HAT,
                               zygosity_pcrelate)]
  src1_merge <- src1_merge[!duplicated(pair_key)]
  master <- merge(master, src1_merge, by = "pair_key", all.x = TRUE)
} else {
  master[, `:=`(source1_pcrelate = NA, kin_pcrelate = NA,
                k0_pcrelate = NA, k1_pcrelate = NA, k2_pcrelate = NA,
                pihat_pcrelate = NA, zygosity_pcrelate = NA_character_)]
}

# --- Merge Source 2: ABCD pihat ---
if (nrow(src2_pairs) > 0) {
  src2_merge <- src2_pairs[, .SD, .SDcols = intersect(
    names(src2_pairs),
    c("pair_key", "source2_abcd_pihat", "pihat_abcd", "zygosity_abcd",
      "zygosity_abcd_code")
  )]
  src2_merge <- src2_merge[!duplicated(pair_key)]
  master <- merge(master, src2_merge, by = "pair_key", all.x = TRUE)
} else {
  master[, `:=`(source2_abcd_pihat = NA, pihat_abcd = NA,
                zygosity_abcd = NA_character_, zygosity_abcd_code = NA_integer_)]
}

# --- Merge Source 3: Demographics ---
if (nrow(src3_pairs) > 0) {
  src3_merge <- src3_pairs[, .(pair_key, source3_demo,
                               rel_birth_id, rel_family_id,
                               birth_group_type)]
  src3_merge <- src3_merge[!duplicated(pair_key)]
  master <- merge(master, src3_merge, by = "pair_key", all.x = TRUE)
} else {
  master[, `:=`(source3_demo = NA, rel_birth_id = NA_character_,
                rel_family_id = NA_character_, birth_group_type = NA_character_)]
}

# Replace NAs in source flags with FALSE
master[is.na(source1_pcrelate), source1_pcrelate := FALSE]
master[is.na(source2_abcd_pihat), source2_abcd_pihat := FALSE]
master[is.na(source3_demo), source3_demo := FALSE]

# Count confirming sources
master[, n_sources := source1_pcrelate + source2_abcd_pihat + source3_demo]

# =============================================================================
# DETERMINE TWIN STATUS AND ZYGOSITY (CONSENSUS)
# =============================================================================

cat("Determining consensus twin status and zygosity...\n\n")

# A pair is a TWIN if:
#   - MZ by genetics (kinship ~ 0.5) — can only be twins, never mere siblings
#   - Same birth ID (Source 3) — same birthdate within family = twins
#   - ABCD zygosity code 1 (MZ) or 2 (DZ) — explicitly classified as twin
#
# A pair is NOT a twin if:
#   - ABCD zygosity code 3 (sibling) — explicitly classified as non-twin sibling
#   - DZ-level kinship but different birth dates → regular full sibling

master[, is_twin := FALSE]

# MZ from PCRelate are definitively twins
master[zygosity_pcrelate == "MZ", is_twin := TRUE]

# Same birth ID = twins
master[source3_demo == TRUE, is_twin := TRUE]

# ABCD classifies as MZ or DZ (code 1 or 2) → twins
master[source2_abcd_pihat == TRUE & zygosity_abcd %in% c("MZ", "DZ"),
       is_twin := TRUE]

# ABCD explicitly says "sibling" (code 3) AND no birth ID match → NOT twin
master[zygosity_abcd == "sibling" & source3_demo == FALSE, is_twin := FALSE]

# DZ_or_sib from PCRelate WITHOUT birth ID or ABCD twin classification → sibling
master[zygosity_pcrelate == "DZ_or_sib" & source3_demo == FALSE &
         !(zygosity_abcd %in% c("MZ", "DZ")),
       is_twin := FALSE]

# --- Consensus zygosity ---
master[, zygosity_consensus := NA_character_]

# MZ if ANY genetic source says MZ
master[zygosity_pcrelate == "MZ" | zygosity_abcd == "MZ",
       zygosity_consensus := "MZ"]

# DZ if confirmed twin + DZ-level kinship
master[is.na(zygosity_consensus) & is_twin == TRUE &
         (zygosity_pcrelate == "DZ_or_sib" | zygosity_abcd == "DZ"),
       zygosity_consensus := "DZ"]

# Twin by birth ID but no genetic data → unknown zygosity
master[is.na(zygosity_consensus) & is_twin == TRUE,
       zygosity_consensus := "Unknown"]

# --- Flag zygosity disagreements ---
master[, zygosity_agreement := NA_character_]
master[!is.na(zygosity_pcrelate) & !is.na(zygosity_abcd) & zygosity_abcd != "Unknown",
       zygosity_agreement := fcase(
         zygosity_pcrelate == "MZ" & zygosity_abcd == "MZ", "agree_MZ",
         zygosity_pcrelate == "DZ_or_sib" & zygosity_abcd == "DZ", "agree_DZ",
         zygosity_pcrelate == "DZ_or_sib" & zygosity_abcd == "sibling", "agree_sibling",
         zygosity_pcrelate == "MZ" & zygosity_abcd == "DZ", "DISAGREE_PCRelate_MZ_ABCD_DZ",
         zygosity_pcrelate == "MZ" & zygosity_abcd == "sibling", "DISAGREE_PCRelate_MZ_ABCD_sib",
         zygosity_pcrelate == "DZ_or_sib" & zygosity_abcd == "MZ", "DISAGREE_PCRelate_DZ_ABCD_MZ",
         default = "partial"
       )]

# =============================================================================
# SUMMARY
# =============================================================================

cat("=============================================================\n")
cat("RESULTS SUMMARY\n")
cat("=============================================================\n\n")

twins_only <- master[is_twin == TRUE]
not_twins  <- master[is_twin == FALSE]
twin_individuals <- unique(c(twins_only$id1, twins_only$id2))

mz_pairs <- twins_only[zygosity_consensus == "MZ"]
dz_pairs <- twins_only[zygosity_consensus == "DZ"]
mz_indiv <- unique(c(mz_pairs$id1, mz_pairs$id2))
dz_indiv <- unique(c(dz_pairs$id1, dz_pairs$id2))

cat("TWIN PAIRS:", nrow(twins_only), "\n")
cat("NON-TWIN RELATED PAIRS:", nrow(not_twins), "\n")
cat("TOTAL TWIN INDIVIDUALS:", length(twin_individuals), "\n\n")

cat("BY ZYGOSITY:\n")
print(table(twins_only$zygosity_consensus, useNA = "ifany"))
cat("\n  MZ:", nrow(mz_pairs), "pairs,", length(mz_indiv), "individuals\n")
cat("  DZ:", nrow(dz_pairs), "pairs,", length(dz_indiv), "individuals\n")

cat("\nBY NUMBER OF CONFIRMING SOURCES:\n")
print(table(twins_only$n_sources))

cat("\nZYGOSITY AGREEMENT BETWEEN PCRelate AND ABCD:\n")
print(table(twins_only$zygosity_agreement, useNA = "ifany"))

disagreements <- twins_only[grepl("DISAGREE", zygosity_agreement)]
if (nrow(disagreements) > 0) {
  cat("\n!! WARNING:", nrow(disagreements), "pairs with ZYGOSITY DISAGREEMENT:\n")
  print(disagreements[, .(pair_key, zygosity_pcrelate, zygosity_abcd,
                          kin_pcrelate, k0_pcrelate, k2_pcrelate)])
} else {
  cat("\nNo zygosity disagreements between sources.\n")
}

# Triplets
triplets <- twins_only[birth_group_type == "triplet"]
if (nrow(triplets) > 0) {
  cat("\nTRIPLETS:", length(unique(triplets$rel_birth_id)), "sets,",
      nrow(triplets), "pairs\n")
}

# Single-source pairs
single_source <- twins_only[n_sources == 1]
if (nrow(single_source) > 0) {
  cat("\nPairs confirmed by ONLY 1 source:", nrow(single_source), "\n")
  cat("  Source 1 only (PCRelate):", sum(single_source$source1_pcrelate &
                                           !single_source$source2_abcd_pihat & !single_source$source3_demo), "\n")
  cat("  Source 2 only (ABCD pihat):", sum(!single_source$source1_pcrelate &
                                             single_source$source2_abcd_pihat & !single_source$source3_demo), "\n")
  cat("  Source 3 only (demographics):", sum(!single_source$source1_pcrelate &
                                               !single_source$source2_abcd_pihat & single_source$source3_demo), "\n")
}

# =============================================================================
# COMPARISON WITH PUBLISHED NUMBERS
# =============================================================================

cat("\n-------------------------------------------------------------\n")
cat("COMPARISON WITH PUBLISHED STUDIES\n")
cat("-------------------------------------------------------------\n\n")

# Update with your own reference numbers as appropriate
comparison <- data.table(
  Study = c("Chen et al. 2025 (HLM, Rel 4.0)",
            "Smith et al. 2023 (FEMA)",
            "This analysis (genetic ID, Rel 5.1)"),
  MZ_individuals = c(461, 408, length(mz_indiv)),
  DZ_individuals = c(641, 516, length(dz_indiv)),
  Total = c(1102, 924, length(twin_individuals)),
  MZ_pairs = c("~230", "204", as.character(nrow(mz_pairs))),
  DZ_pairs = c("~320", "258", as.character(nrow(dz_pairs)))
)
print(comparison)

cat("\nNote: Larger numbers may reflect genetic identification across the full\n")
cat("ABCD sample (including general-population twins) rather than only the\n")
cat("designated twin-hub subsample.\n")

# =============================================================================
# SOURCE-LEVEL COMPARISON
# =============================================================================

cat("\n-------------------------------------------------------------\n")
cat("SOURCE-LEVEL PAIR COMPARISON\n")
cat("-------------------------------------------------------------\n\n")

src1_twin_keys <- if (nrow(src1_pairs) > 0) src1_pairs[zygosity_pcrelate == "MZ" | 
                                                         (zygosity_pcrelate == "DZ_or_sib" & pair_key %in% twins_only$pair_key), pair_key] else character()
src2_twin_keys <- if (nrow(src2_pairs) > 0) src2_pairs[zygosity_abcd %in% c("MZ", "DZ"), pair_key] else character()
src3_twin_keys <- if (nrow(src3_pairs) > 0) src3_pairs$pair_key else character()

cat("Twin pairs by source:\n")
cat("  Source 1 (PCRelate):         ", length(src1_twin_keys), "\n")
cat("  Source 2 (gen_y_pihat):      ", length(src2_twin_keys), "\n")
cat("  Source 3 (cleaned abcd_y_lt):", length(src3_twin_keys), "\n\n")

cat("Overlap:\n")
cat("  Src1 ∩ Src2:", length(intersect(src1_twin_keys, src2_twin_keys)), "\n")
cat("  Src1 ∩ Src3:", length(intersect(src1_twin_keys, src3_twin_keys)), "\n")
cat("  Src2 ∩ Src3:", length(intersect(src2_twin_keys, src3_twin_keys)), "\n")
cat("  All three:  ", length(Reduce(intersect, list(src1_twin_keys, src2_twin_keys, src3_twin_keys))), "\n\n")

cat("Unique to one source only:\n")
cat("  PCRelate only:           ", length(setdiff(src1_twin_keys, union(src2_twin_keys, src3_twin_keys))), "\n")
cat("  gen_y_pihat only:        ", length(setdiff(src2_twin_keys, union(src1_twin_keys, src3_twin_keys))), "\n")
cat("  cleaned abcd_y_lt only:  ", length(setdiff(src3_twin_keys, union(src1_twin_keys, src2_twin_keys))), "\n")

# =============================================================================
# SAVE OUTPUTS
# =============================================================================

cat("\n-------------------------------------------------------------\n")
cat("SAVING OUTPUTS\n")
cat("-------------------------------------------------------------\n\n")

fwrite(master, file.path(OUTPUT_DIR, "all_twin_pairs_crosschecked.csv"))
cat("  All pairs (cross-checked): all_twin_pairs_crosschecked.csv\n")

fwrite(twins_only, file.path(OUTPUT_DIR, "confirmed_twins_all.csv"))
cat("  Confirmed twins: confirmed_twins_all.csv\n")

fwrite(mz_pairs, file.path(OUTPUT_DIR, "mz_twins_final.csv"))
cat("  MZ twins: mz_twins_final.csv\n")

fwrite(dz_pairs, file.path(OUTPUT_DIR, "dz_twins_final.csv"))
cat("  DZ twins: dz_twins_final.csv\n")

fwrite(not_twins, file.path(OUTPUT_DIR, "non_twin_siblings.csv"))
cat("  Non-twin siblings: non_twin_siblings.csv\n")

# Individual-level twin list
twin_indiv_dt <- data.table(src_subject_id = twin_individuals)
twin_indiv_dt[, is_MZ := src_subject_id %in% mz_indiv]
twin_indiv_dt[, is_DZ := src_subject_id %in% dz_indiv]
twin_indiv_dt[, zygosity := fcase(
  is_MZ & !is_DZ, "MZ",
  !is_MZ & is_DZ, "DZ",
  is_MZ & is_DZ,  "MZ+DZ_multiplet",
  default = "Unknown"
)]
fwrite(twin_indiv_dt, file.path(OUTPUT_DIR, "twin_individuals.csv"))
cat("  Individual twin list: twin_individuals.csv\n")

# Summary text file
summary_file <- file.path(OUTPUT_DIR, "twin_crosscheck_summary.txt")
sink(summary_file)
cat("ABCD Twin Cross-Check Summary\n")
cat("Generated:", format(Sys.time()), "\n\n")
cat("Sources:\n")
cat("  1. PCRelate:", PCRELATE_FILE, "\n")
cat("  2. ABCD gen_y_pihat:", PIHAT_FILE, "\n")
cat("  3. Cleaned demographics:", DEMO_FILE, "\n\n")
cat("Thresholds:\n")
cat("  MZ: kinship >", MZ_KIN_MIN, ", k0 <", MZ_K0_MAX, "\n")
cat("  DZ: kinship", DZ_KIN_MIN, "-", DZ_KIN_MAX, "\n\n")
cat("Results:\n")
cat("  MZ:", nrow(mz_pairs), "pairs (", length(mz_indiv), "individuals)\n")
cat("  DZ:", nrow(dz_pairs), "pairs (", length(dz_indiv), "individuals)\n")
cat("  Total twin individuals:", length(twin_individuals), "\n")
if (nrow(triplets) > 0) cat("  Triplet sets:", length(unique(triplets$rel_birth_id)), "\n")
cat("  Zygosity disagreements:", nrow(disagreements), "\n")
cat("  Single-source-only pairs:", nrow(single_source), "\n")
sink()
cat("  Summary: twin_crosscheck_summary.txt\n")

cat("\nDone!\n")
cat("=============================================================\n")
